networks:
  events-network:
    driver: bridge

services:
  mongo:
    container_name: event-ms-mongo
    image: 'mongo:latest'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    ports:
      - '27017:27017'
    networks:
      - events-network